# Default values for memory-gateway.
# This is a YAML-formatted file.

# Specify the namespace where this service will be deployed
# Leave empty to use the namespace specified in the helm command
namespace: "default"

# Replica count for scaling
replicaCount: 1

# These values will be pulled from an overlay file. 
aws:
  region: ""
  account: ""

# Memory provider configuration
memoryProvider:
  type: "postgres"  # Options: "postgres", "bedrock_agentcore"
  
  # Bedrock AgentCore Memory specific configuration
  bedrockAgentCore:
    region: "us-west-2"
    memoryId: ""  # Optional: ID of an existing memory resource

image:
  repository: "agentic-platform-memory-gateway"
  tag: latest
  pullPolicy: Always

nameOverride: "memory-gateway"
fullnameOverride: "memory-gateway"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  - name: PYTHONPATH
    value: /app
  # The following environment variables will be set by the template based on memoryProvider configuration
  # - name: MEMORY_PROVIDER
  #   value: postgres or bedrock_agentcore
  # - name: AWS_REGION (if using bedrock_agentcore)
  #   value: region
  # - name: BEDROCK_AGENTCORE_MEMORY_ID (if using bedrock_agentcore and memoryId is provided)
  #   value: memoryId

# Resource allocation
resources:
  requests:
    cpu: 100m      # 0.1 CPU core (10% of a core)
    memory: 256Mi  # 256 megabytes
  limits:
    memory: 512Mi  # 512 megabytes

# Ingress configuration
ingress:
  enabled: true
  path: "/memory-gateway"

# Service account for permissions
serviceAccount:
  name: "memory-gateway-sa"
  create: true

# Memory gateway role
irsaConfigKey: MEMORY_GATEWAY_ROLE_ARN
