{{- $configMap := (lookup "v1" "ConfigMap" .Values.namespace "agentic-platform-config") -}}
{{- if $configMap -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-secret
  namespace: {{ include "app.namespace" . }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ include "app.name" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "app.name" . }}-agent-secret 
    creationPolicy: Owner
  data:
    - secretKey: "LITELLM_KEY"
      remoteRef:
        key: {{ index $configMap.data .Values.agentSecret.configKey }}
        property: "LITELLM_KEY"
{{- end }}
