{{- if eq .Release.Name "memory-gateway" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ include "app.namespace" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            - name: MEMORY_PROVIDER
              value: {{ .Values.memoryProvider.type | quote }}
            {{- if eq .Values.memoryProvider.type "bedrock_agentcore" }}
            - name: AWS_REGION
              value: {{ .Values.memoryProvider.bedrockAgentCore.region | quote }}
            {{- if .Values.memoryProvider.bedrockAgentCore.memoryId }}
            - name: BEDROCK_AGENTCORE_MEMORY_ID
              value: {{ .Values.memoryProvider.bedrockAgentCore.memoryId | quote }}
            {{- end }}
            {{- end }}
{{- end }}
